builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - linux
      - windows
      - darwin
    goarch:
      - amd64
      - arm64
    binary: tigris
    flags:
      - -tags=release,tigris_grpc,tigris_http
    ldflags:
      - -w -extldflags '-static'
      - -X 'github.com/tigrisdata/tigris-cli/util.Version={{.Version}}'

archives:
  - format_overrides:
      - goos: windows
        format: zip
    name_template: "tigris_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    files:
      - src: ./.tmp/bash.completions
        dst: completion/bash/tigris
      - src: ./.tmp/fish.completions
        dst: completion/fish/tigris
      - src: ./.tmp/zsh.completions
        dst: completion/zsh/_tigris

checksum:
  name_template: 'checksums.txt'
signs:
  - artifacts: checksum
changelog:
  skip: true

nfpms:
  - formats:
      - apk
      - deb
      - rpm
      - termux.deb
    file_name_template: "tigris_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    maintainer: Yevgeniy Firsov <firsov@tigrisdata.com>
    contents:
      - src: ./.tmp/bash.completions
        dst: /etc/bash_completion.d/tigris
      - src: ./.tmp/fish.completions
        dst: /usr/share/fish/completions/tigris.fish
      - src: ./.tmp/zsh.completions
        dst: /usr/local/share/zsh/site-functions/_tigris

brews:
  - tap:
      owner: tigrisdata
      name: homebrew-tigris
    folder: Formula
    homepage: "https://docs.tigrisdata.com"
    description: "Tigris is a modern, scalable backend for building real-time websites and apps."
    license: Apache-2.0
    install: |-
      bin.install "tigris"
      bash_completion.install "completion/bash/tigris" => "tigris"
      zsh_completion.install "completion/zsh/_tigris" => "_tigris"
      fish_completion.install "completion/fish/tigris"
