version: '3.3'

services:
  tigris:
    container_name: tigris-local-server
    image: tigrisdata/tigris-local
    ports:
      - "8081:8081"

  service:
    container_name: tigris_{{.DBName}}
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      - TIGRIS_URL=tigris-local-server:8081
    ports:
      - "3000:3000"
    depends_on:
      - tigris
