server:
  port: 8080

tigris:
  db:
    name: "{{.DBName}}"
  server:
    url: "localhost:8081"
  network:
    usePlainText: true
  authorization:
    token: "some-token"

springdoc:
  swagger-ui:
    path: "/swagger.html"
    operationsSorter: "method"