# https://taskfile.dev

version: '3'

tasks:
  default:
    cmds:
      - task -l
    silent: true

  run:
    desc: Run {{.DBName}} in the development environment
    deps: [deps]
    cmds:
        - bin/tigris dev start
        - TIGRIS_URL=localhost:8081 go run main.go

  deps:
    desc: Install dependencies
    status:
      - test -x bin/tigris
    cmds:
      - mkdir -p bin
      - curl -sSL https://tigris.dev/cli-{{`{{if eq OS "darwin"}}macos{{else}}{{OS}}{{end}}{{if eq ARCH "arm"}}-arm64{{end}}`}} | tar -xz -C ./bin

  clean:
    desc: Cleanup the resources
    cmds:
      - bin/tigris dev stop
